apiVersion: batch/v1
kind: CronJob
metadata:
  name: port-scanner
  namespace: blue
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            is_anomaly: true
            app: port-scanner
        spec:
          containers:
            - name: port-scanner
              image: nicolaka/netshoot
              command: ["/bin/bash", "-c"]
              args:
                - |
                  subnet="10.0.0"
                  for i in {1..254}; do
                    ip="${subnet}.${i}"
                    nmap -Pn -T5 --max-retries 1 --host-timeout 100ms -p- $ip &> /dev/null
                    if [ $? -eq 0 ]; then
                      echo "Scanning $ip"
                      nmap -T5 -p- $ip
                    else
                      echo "$ip is down"
                    fi
                  done
              imagePullPolicy: Always
          restartPolicy: OnFailure
